@startuml
skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 0
left to right direction
skinparam backgroundColor white
skinparam ArrowFontSize 15
skinparam ArrowFontBackgroundColor White


' skinparam ArrowThickness 2
title Architecture of Podman
legend "Legend: Naming scheme: "Organisation | ProjectName""
folder "OCI-Compliant Runtimes" as oci_runtime_tools_ {
    component "opencontainers | Runc" as runc_
    component "containers | Crun" as crun_
}
interface "opencontainers | OCI Configuration" as oci_config_
interface "OCI Compliant container" as oci_container_
interface "OCI Compliant image" as oci_image_

component "CRI-O | CRI-O" as crio_
component "containers | Podman Desktop" as podman_desktop_
component "containers | Podman" as podman_
interface "containers | Seccomp" as seccomp_
component "opencontainers | runtime-tools" as runtime_tools_

interface "containers | Container" as pod_container_

component "CRIU | CRIU" as criu_

package Libpod as libpod_ {
    component "containers | Buildah" as buildah_
    component "containers | Image" as image_
    component "containers | gvisor-tap-vsock" as gvisor_
    component "containers | Storage" as storage_
    interface "containers | common/libimage" as pod_image_
    component "containers | Conmon" as conmon_
    package "Networking" as networking_ {
        component "containers | Netavark" as netavark_
        component "containers | Aardvark (DNS)" as aardvark_
        component "passt | pasta" as pasta_
        component "rootless-containers | slirp4netns" as slirp4netns_
    }
' component "containers | Podman" as Podman
}
' Updated connections (you might need to adjust ordering or add further placement hints)
' Buildah -> OCIRuntimeTools
' Podman -> OCIRuntimeTools


buildah_ "builds" --> pod_image_
buildah_ "implements" ..> seccomp_
podman_desktop_ -left-> podman_
podman_ --> libpod_

image_ "manages" --> pod_image_

conmon_ "monitors" --> oci_runtime_tools_

' Note: Ensure the component names match the alias names defined above
runtime_tools_ "generates" -left-> oci_config_
oci_runtime_tools_ .right.> oci_config_

crio_ --> conmon_
crio_ ..> seccomp_ : implements

' Podman --> OCIImage : maintain and modifies
' Podman --> OCIContainer : maintain and modifies
libpod_ ..>  seccomp_
libpod_ --> criu_
libpod_ --> runtime_tools_
libpod_ --> "creates" pod_container_
pod_image_  ..> "implements" oci_image_
pod_container_  ..>  "implements" oci_container_
' Podman --> Runtimetools : uses
' Podman --> CRIU : restoration

' Podman -> gvisor
' Podman -> Conmon
' Podman -> Buildah
' Podman -> pasta
' Podman -> slirp4netns
' Podman -> Aardvark
' Podman -> Netavark
' Podman -> Storage
' Podman -> Image
' Podman -> CRIU

' Note section
note left of [image_]
Handles Image management
end note
note left of [storage_]
Handles Container and image storage
end note
note left of networking_
Networking support through Netavark and Aadvark.
Rootless networking is handled via pasta or slirp4netns
end note

note left of [buildah_]
Builds are supported via Buildah
end note

note left of [conmon_]
Monitors OCI runtimes, used by both Podman and CRI-O.
end note

note right of seccomp_
A unified policy for Podman, Buildah, and CRI-O.
end note

note right of criu_
Handles checkpointing and restoring for containers
end note

note left of libpod_ #Crimson
Important:
To improve the visual appeal of this diagram, all dependencies associated 
with Libpod have been grouped into a single Libpod module. 

In a more detailed representation, each dependency would be explicitly 
shown as an individual arrow originating from Libpod and pointing to the 
respective component.
end note
@enduml